[package]
name = "toy-arms-test"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
bindings = { path = "../toy-arms/bindings/" }
windows = "0.19.0"
tokio = { version = "1.11.0", features = ["full"] }
toy-arms = { path = "../toy-arms" }