[package]
name = "toy-arms-test"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi", "consoleapi"] }
toy-arms = {path = "../toy-arms"}
static_init = "1.0.1"