[package]
name = "toy-arms-test"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
bindings = {package = "toy-arms-bindings", path = "../toy-arms/bindings/" }
windows = "0.19.0"
toy-arms = { path = "../toy-arms" }